version: "2.1"
services:
  wireguard:
    image: wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=vpn.vorprog.com
      - PEERS=1
      # - PEERDNS=auto
      - INTERNAL_SUBNET=10.0.0.0
      - ALLOWEDIPS=10.0.0.0/8
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    command: ./entrypoint.sh
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
